# Generated by Django 2.2.1 on 2019-05-22 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190522_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
