# Generated by Django 2.2.1 on 2019-05-22 09:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190522_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
